# 102 x 100
tile = (
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GG                                                                                                GG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
)
