tile = (
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                                      GG',
    'GG                             GG       GG',
    'GG                            GGGGG     GG',
    'GG                             GG       GG',
    'GG             GGGGGG     G    GG       GG',
    'GG            GGGGGG     GG    GG       GG',
    'GG           GGGG              GGGG     GG',
    'GG                             GG       GG',
    'GG                             GG     GGGG',
    'GG                             GG       GG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG'
)
